apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "java-demo.name" . }}-config
  labels:
    {{- include "java-demo.labels" . | nindent 4 }}
data:
  GREETING: {{ .Values.config.greeting | quote }}
