apiVersion: v1
kind: Secret
metadata:
  name: {{ include "java-demo.name" . }}-secret
  labels:
    {{- include "java-demo.labels" . | nindent 4 }}
type: Opaque
stringData:
  API_TOKEN: {{ .Values.secret.apiToken | quote }}
