apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: java-demo-dev
  namespace: argocd
spec:
  project: default

  source:
    repoURL: "https://github.com/DITT_BRUKERNAVN/k8s-argocd-java-demo.git"
    targetRevision: main
    path: chart/java-demo
    helm:
      valueFiles:
        - ../../environments/dev/values.yaml

  destination:
    server: "https://kubernetes.default.svc"
    namespace: demo

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
